### ISSUE TITLE
Can I contribute as a collaborator of this repo?

### ISSUE THREAD

**Issue by henry-yeh** [AGI-Edgerunners/LLM-Optimizers-Papers#5]
Awesome works @AGI-Edgerunners!
I noticed that this repo has not been updated recently. Could you make me a collaborator of this repo so that I can commit updates more easily? @demoleiwang

**Comment by demoleiwang** [comment]
Absolutely! It's great that we can work together to maintain this repository. I have invited you as a collaborator. This will make it much easier for you to make updates whenever you want to.

Thanks!
